spring:

#  redis:
#    host: 127.0.0.1
#    port: 6379
  config:
    import: custom/setting.yml

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create

  cache:
    type: redis
    redis:
      time-to-live: 600000
